"""
""" .vimrc
"""

set nocompatible
filetype plugin on

set t_Co=256

" Don't use .viminfo file
set viminfo=
set backspace=indent,eol,start

"" Encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=utf-8,cp932,iso-2022-jp,euc-jp
if has("win32") || has("win64")
  set fileformats=dos,unix,mac
else
  set fileformats=unix,dos,mac
endif

"" Save
set nobackup
set nowritebackup
" Preserve metadata when saving a file
set backupcopy=yes

"" Search
set ignorecase
set smartcase
set wrapscan
set noincsearch

"" modeline
set modeline
set modelines=5

"" Tab and indent
set tabstop=4
set expandtab
set smartindent
set shiftwidth=4
set softtabstop=4

set autochdir

"" Display
syntax enable
set background=dark
colorscheme default
highlight CursorLine    cterm=underline ctermfg=NONE ctermbg=NONE term=NONE
highlight LineNr        cterm=NONE ctermfg=8 ctermbg=0
highlight CursorLineNr  cterm=NONE ctermfg=0 ctermbg=8
highlight NonText       cterm=NONE ctermfg=8 ctermbg=NONE
highlight SpecialKey    cterm=NONE ctermfg=8 ctermbg=NONE
highlight Search        cterm=NONE ctermfg=0 ctermbg=11
set showmatch
set ruler
set list
set listchars=tab:>.,extends:<,trail:-,eol:$
"set listchars=tab:│┈,extends:<,trail:-,eol:$
set showcmd
set cmdheight=1
set notitle
set showtabline=1
set hlsearch
set number
set numberwidth=6
set textwidth=0

set cursorline
"set cursorcolumn

"" Print
set printoptions=number:y

"" Filename completion
set wildmenu

"" Spell checking
setlocal spell spelllang=en_us
if has("win32") || has("win64")
  set spellfile=~\vimfiles\spell.utf-8.add
else
  set spellfile=~/.vim/spell.utf-8.add
endif
set nospell

"" Per-FileType settings
autocmd FileType ruby set ts=2 sw=2 sts=2
autocmd FileType html set ts=2 sw=2 sts=2
autocmd FileType xhtml set ts=2 sw=2 sts=2
autocmd FileType javascript set ts=2 sw=2 sts=2
autocmd FileType css set ts=2 sw=2 sts=2

"" Change encoding
command! -nargs=0 Encjis e ++enc=iso-2022-jp
command! -nargs=0 Encsjis e ++enc=cp932
command! -nargs=0 Enceuc e ++enc=euc-jp
command! -nargs=0 Encutf8 e ++enc=utf-8

"" Status line
set laststatus=2
"set statusline=[%n]\ %t\ %y%{GetStatusEx()}%m%r%=%l,%c%V\ \ \ \ %P
set statusline=[%n%{bufnr('$')>1?'/'.bufnr('$'):''}%{winnr('$')>1?':'.winnr().'/'.winnr('$'):''}]\ %t\ %y%{GetStatusEx()}%m%r%=%l,%c%V\ \ \ \ %P
function! GetStatusEx()
    let str = &fileformat
    if has("multi_byte") && &fileencoding != ""
        let str = &fileencoding . ":" . str
    endif
    let str = "[" . str . "]"
    return str
endfunction

"" Code folding
set nofoldenable

"" Toggle number/relativenumber
function! ToggleLineNumberDisplayMode()
    if &relativenumber == 1
        set number
        set norelativenumber
    else
        set number
        set relativenumber
    endif
endfunction
nnoremap <silent> ,n :call ToggleLineNumberDisplayMode()<CR>
